/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MathCommandPane.java
 *
 * Created on Aug 27, 2011, 6:42:38 PM
 */

package gui;
 
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author JIBOYE OLUWAGBEMIRO OLAOLUWA
 */
public class MathCommandPane extends javax.swing.JPanel {
/**
 * The caret's instantaneous vertical location.
 */
    private int caretVerticalPosition=0;
  

    /** Creates new form MathCommandPane */
    public MathCommandPane() {
        initComponents();
        final Caret c = new DefaultCaret();
        c.setVisible(true);
        c.setBlinkRate(500);
        c.install(commandArea);
        commandArea.setCaret(c);
        commandArea.setCaretColor(Color.red);
        c.setSelectionVisible(false);
        c.setVisible(true);
commandArea.setText("cmd>> ");
c.moveDot(1);

        






        c.addChangeListener( new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
        c.setSelectionVisible(true);
        c.setVisible(true);
      
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneArea = new javax.swing.JScrollPane();
        commandArea = new javax.swing.JTextArea();

        setName("Form"); // NOI18N

        scrollPaneArea.setName("scrollPaneArea"); // NOI18N

        commandArea.setColumns(20);
        commandArea.setEditable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(MathCommandPane.class);
        commandArea.setFont(resourceMap.getFont("commandArea.font")); // NOI18N
        commandArea.setRows(5);
        commandArea.setText(resourceMap.getString("commandArea.text")); // NOI18N
        commandArea.setName("commandArea"); // NOI18N
        commandArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commandAreaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                commandAreaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                commandAreaMouseReleased(evt);
            }
        });
        commandArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commandAreaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                commandAreaKeyTyped(evt);
            }
        });
        scrollPaneArea.setViewportView(commandArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(scrollPaneArea, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneArea, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setCaretVerticalPosition(int caretVerticalPosition) {
int lineCount =commandArea.getLineCount();
        this.caretVerticalPosition =
( caretVerticalPosition>=0 && caretVerticalPosition<=lineCount )?caretVerticalPosition:lineCount;
    }

    public int getCaretVerticalPosition() {
        return caretVerticalPosition;
    }




 

/**
 *
 * @param numOfChars The number of characters at most to be copied.
 * @return the next <b color ='red'>'numOfChars'</b> characters relative
 * to the current position of this text editor's caret.
 */
private String copyNextNChars(  int numOfChars ){
    Caret c = commandArea.getCaret();
int dot = c.getDot();
String chars="";
for( int i=0; i<numOfChars;i++){
            try {
                chars += commandArea.getText(dot+i, 1);
            } catch (BadLocationException ex) {
            }
}//end for loop
return chars;
}

/**
 *
 * @param numOfChars The number of characters at most to be copied.
 * @return the previous <b color ='red'>'numOfChars'</b> characters relative
 * to the current position of this text editor's caret.
 */
private String copyPrevNChars(  int numOfChars ){
    Caret c = commandArea.getCaret();
int dot = c.getDot();
String chars="";
dot-=(numOfChars);
for( int i=0; i<numOfChars;i++){
            try {
                chars += commandArea.getText(dot+i, 1);
            }//end try
            catch (BadLocationException ex) {
            }
}//end for loop
return chars;
}



private boolean caretIsOnCmdText( Caret c ){
String prevLetter = copyPrevNChars(1);
String prevTwoLetters = copyPrevNChars(2);
String prevThreeLetters = copyPrevNChars(3);
String prevFourLetters = copyPrevNChars(4);
String prevFiveLetters = copyPrevNChars(5);


String nextLetter =       copyNextNChars(1);
String nextTwoLetters =   copyNextNChars(2);
String nextThreeLetters = copyNextNChars(3);
String nextFourLetters =  copyNextNChars(4);
String nextFiveLetters =  copyNextNChars(5);

/*
System.out.println("prevLetter = "+prevLetter+" nextLetter = "+ nextLetter);
System.out.println("prevTwoLetters = "+prevTwoLetters+" nextTwoLetters = "+ nextTwoLetters);
System.out.println("prevThreeLetters = "+prevThreeLetters+" nextThreeLetters = "+ nextThreeLetters);
System.out.println("prevFourLetters = "+prevFourLetters+" nextFourLetters = "+ nextFourLetters);
System.out.println("prevFiveLetters = "+prevFiveLetters+" nextFiveLetters = "+ nextFiveLetters);
*/

if(  nextFiveLetters.equals("cmd>>")){
    return true;
    }
else if( prevLetter.equals( "c") && nextFourLetters.equals("md>>")){
    return true;
}
else if( prevTwoLetters.equals("cm") && nextThreeLetters.equals("d>>")){
    return true;
}
else if( prevThreeLetters.equals("cmd") && nextTwoLetters.equals(">>")){
    return true;
}
else if( prevFourLetters.equals("cmd>") && nextLetter.equals(">")){
    return true;
}
else if( prevFiveLetters.equals("cmd>>") ){commandArea.copy();
    return true;
}
 else{
     return false;
 }





  //  }//end try
//catch(BadLocationException ble){
  //  return true;
//}
}


    private void commandAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commandAreaKeyTyped
String input = String.valueOf( evt.getKeyChar() );
Caret c = commandArea.getCaret();
int dot = c.getDot();
int mark = c.getMark();
String evtdata = evt.paramString().toLowerCase();
if(!caretIsOnCmdText(c)){
if(input.length()==1 &&!evtdata.contains("backspace")&&!evtdata.contains("delete")&&!evtdata.contains("escape")
        &&!evtdata.contains("enter")){
commandArea.insert(input,dot);
c.moveDot(dot+1);
}

else if(input.length() == 1 && evtdata.contains("backspace")){
     
//backspace action!
if( !caretIsOnCmdText(c) ){

    if(dot == mark && dot!=0){
        --dot;
    }
//System.out.printf("%10s%10s\n",dot,mark);
commandArea.replaceRange("",dot,mark);
c.moveDot(dot);
//commandArea.set
    }
        }//end else if

        }//end if caretIsOnCmd
if (evtdata.contains("enter")) {
     commandArea.append("\ncmd>> ");
     //commandArea.getCaret().setMagicCaretPosition();
 }
    }//GEN-LAST:event_commandAreaKeyTyped

    private void commandAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandAreaMouseClicked

    }//GEN-LAST:event_commandAreaMouseClicked

    private void commandAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandAreaMousePressed
  try{
              if(evt.getButton()==1){//normal click
                  setCaretVerticalPosition(commandArea.getCaret().getMark());
                  System.out.println("ypos of caret = "+caretVerticalPosition);
              }
              else if(evt.getButton()==3){//rightclick or meta

              }
                }//end try
                catch(NullPointerException nol){

                }
    }//GEN-LAST:event_commandAreaMousePressed

    private void commandAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandAreaMouseReleased

    }//GEN-LAST:event_commandAreaMouseReleased

    private void commandAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commandAreaKeyPressed
String input = KeyEvent.getKeyText(evt.getKeyCode()).toLowerCase();
int lineCount = commandArea.getLineCount();
if( input.equals("up")){
 try{
    Caret c = commandArea.getCaret();
        Point p = c.getMagicCaretPosition();
           setCaretVerticalPosition(caretVerticalPosition);
            commandArea.moveCaretPosition(caretVerticalPosition);
     
        }//end try
  catch(IllegalArgumentException iae){

  }
catch(NullPointerException nol){

}
}//end if
else if(input.equals("down")){
  try{
    Caret c = commandArea.getCaret();
        Point p = c.getMagicCaretPosition();
           setCaretVerticalPosition(++caretVerticalPosition);
            commandArea.moveCaretPosition(caretVerticalPosition);
      commandArea.getLineCount();
        }//end try
  catch(IllegalArgumentException iae){
           setCaretVerticalPosition(--caretVerticalPosition);
  }
catch(NullPointerException nol){

}
}
 else if(input.equals("enter")){
     try{
    setCaretVerticalPosition(++caretVerticalPosition);
            commandArea.moveCaretPosition(lineCount);

            
}//end try
catch(NullPointerException nol){
    
}

}//end else if

                  System.out.println("cvp = "+caretVerticalPosition);
                  System.out.println("mark = "+commandArea.getCaret().getMark());
                  System.out.println("caret position = "+commandArea.getCaretPosition());
      


    }//GEN-LAST:event_commandAreaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commandArea;
    private javax.swing.JScrollPane scrollPaneArea;
    // End of variables declaration//GEN-END:variables


 public static void main(String args[]){
    JFrame f = new JFrame("Command Prompt");
    MathCommandPane commandPane = new MathCommandPane();

      f.add(commandPane);
     f.setVisible(true);
     f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     f.setSize(1000,900);
     




 }

}