/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContentPanel.java
 *
 * Created on May 26, 2011, 5:49:42 AM
 */

package help;

import java.awt.*;
import java.net.URL;
import javax.swing.JEditorPane;
import javax.swing.event.*;



/**
 *
 *@author JIBOYE Oluwagbemiro Olaoluwa
 */
public class ContentPanel extends javax.swing.JPanel {

private String urlString;

    public ContentPanel() {
        initComponents();
    }



    /** Creates new form ContentPanel */
    public ContentPanel(String urlString) {
        initComponents();
        setUrlString(urlString);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentEditorPane = new javax.swing.JEditorPane();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        contentEditorPane.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        contentEditorPane.setEditable(false);
        contentEditorPane.setName("contentEditorPane"); // NOI18N
        jScrollPane1.setViewportView(contentEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setUrlString(String urlString) {
        this.urlString = urlString;
        openURL(urlString);
    }

    public String getUrlString() {
        return urlString;
    }

    public void setContentEditorPane(JEditorPane contentEditorPane) {
        this.contentEditorPane = contentEditorPane;
    }

    public JEditorPane getContentEditorPane() {
        return contentEditorPane;
    }


protected void openURL(String urlString) {
try {
URL url = new URL(urlString);
contentEditorPane.setPage(url);
contentEditorPane.addHyperlinkListener(new LinkActivator( ));

}
catch (Exception e) {
    e.printStackTrace();
System.out.println("Couldn't open " + urlString + ":" + e);
}
}//end method
class LinkActivator implements HyperlinkListener {
        @Override
public void hyperlinkUpdate(HyperlinkEvent he) {
HyperlinkEvent.EventType type = he.getEventType( );
if (type == HyperlinkEvent.EventType.ENTERED)
contentEditorPane.setCursor(
Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
else if (type == HyperlinkEvent.EventType.EXITED)
contentEditorPane.setCursor(Cursor.getDefaultCursor( ));
else if (type == HyperlinkEvent.EventType.ACTIVATED)
openURL(he.getURL().toExternalForm( ));
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JEditorPane contentEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
