/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpFrame.java
 *
 * Created on May 26, 2011, 5:59:42 AM
 */

package help;

import java.io.File;

/**
 *
 *@author JIBOYE Oluwagbemiro Olaoluwa
 */
public class HelpFrame extends javax.swing.JFrame {

    public HelpFrame() {
        initComponents();
        setResizable(false);
    }

    /** Creates new form HelpFrame */
    public HelpFrame(String linksUrl , String contentUrl) {
        initComponents();
        linksPanel1.setUrlString(linksUrl);
        contentPanel1.setUrlString(contentUrl);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linksPanel1 = new help.LinksPanel();
        contentPanel1 = new help.ContentPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        linksPanel1.setName("linksPanel1"); // NOI18N

        contentPanel1.setName("contentPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(linksPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addComponent(linksPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setContentPanel1(ContentPanel contentPanel1) {
        this.contentPanel1 = contentPanel1;
    }

    public ContentPanel getContentPanel1() {
        return contentPanel1;
    }

    public void setLinksPanel1(LinksPanel linksPanel1) {
        this.linksPanel1 = linksPanel1;
    }

    public LinksPanel getLinksPanel1() {
        return linksPanel1;
    }


    


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        File f1 = new File("src/help/Links.html");
        File f2 = new File("");
        try {
            HelpFrame hFrame = new HelpFrame(  f1.toURI().toString(),f2.toURI().toString());
         hFrame.setVisible(true);
        }
        catch(NullPointerException nol){
            nol.printStackTrace();
        }
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private help.ContentPanel contentPanel1;
    private help.LinksPanel linksPanel1;
    // End of variables declaration//GEN-END:variables

}
