/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinksPanel.java
 *
 * Created on May 26, 2011, 5:43:26 AM
 */

package help;

import java.awt.*;
import java.io.File;
import java.net.URL;
import javax.swing.JEditorPane;
import javax.swing.event.*;

/**
 *
 *@author JIBOYE Oluwagbemiro Olaoluwa
 */
public class LinksPanel extends javax.swing.JPanel {

private String urlString;


    public LinksPanel() {
        initComponents();
        openLinksURL(new File("src/help/Links.html").toURI().toString());
    }



    /** Creates new form LinksPanel */
    public LinksPanel(String urlString) {
        initComponents();
        setUrlString(urlString);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        linksEditorPane = new javax.swing.JEditorPane();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        linksEditorPane.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(LinksPanel.class);
        linksEditorPane.setContentType(resourceMap.getString("linksEditorPane.contentType")); // NOI18N
        linksEditorPane.setEditable(false);
        linksEditorPane.setName("linksEditorPane"); // NOI18N
        jScrollPane1.setViewportView(linksEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setLinksEditorPane(JEditorPane linksEditorPane) {
        this.linksEditorPane = linksEditorPane;
    }

    public JEditorPane getLinksEditorPane() {
        return linksEditorPane;
    }



    public void setUrlString(String urlString) {
        this.urlString = urlString;
        openURL(urlString);
    }

    public String getUrlString() {
        return urlString;
    }

protected void openLinksURL(String urlString) {
try {
URL url = new URL(urlString);
linksEditorPane.setPage(url);
linksEditorPane.addHyperlinkListener(new LinkActivator( ));
}

catch (Exception e) {
    e.printStackTrace();
System.out.println("Couldn't open " + urlString + ":" + e);
}
    }
protected void openURL(String urlString) {
try {
URL url = new URL(urlString);
ContentPanel.contentEditorPane.setPage(url);
linksEditorPane.addHyperlinkListener(new LinkActivator( ));
}

catch (Exception e) {
    e.printStackTrace();
System.out.println("Couldn't open " + urlString + ":" + e);
}
}//end method
class LinkActivator implements HyperlinkListener {
        @Override
public void hyperlinkUpdate(HyperlinkEvent he) {
HyperlinkEvent.EventType type = he.getEventType( );
if (type == HyperlinkEvent.EventType.ENTERED)
ContentPanel.contentEditorPane.setCursor(
Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
else if (type == HyperlinkEvent.EventType.EXITED)
ContentPanel.contentEditorPane.setCursor(Cursor.getDefaultCursor( ));
else if (type == HyperlinkEvent.EventType.ACTIVATED)
openURL(he.getURL().toExternalForm( ));
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane linksEditorPane;
    // End of variables declaration//GEN-END:variables

}
