/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyNameDecoder.java
 *
 * Created on Aug 15, 2010, 7:42:33 PM
 */

package gui.practisepitch;

import java.awt.event.*;

/**
 *
 * @author GBEMIRO
 */
public class KeyNameDecoder extends javax.swing.JFrame {

    /** Creates new form KeyNameDecoder */
    public KeyNameDecoder() {
        super("Get The Key Text On Key Pressed Events!!!!!!!!!");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyPan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keyTextGetter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(KeyNameDecoder.class);
        keyPan.setBackground(resourceMap.getColor("keyPan.background")); // NOI18N
        keyPan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keyPan.setName("keyPan"); // NOI18N
        keyPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                keyPanMousePressed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        keyTextGetter.setText(resourceMap.getString("keyTextGetter.text")); // NOI18N
        keyTextGetter.setDisabledTextColor(resourceMap.getColor("keyTextGetter.disabledTextColor")); // NOI18N
        keyTextGetter.setName("keyTextGetter"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        testArea.setBackground(resourceMap.getColor("testArea.background")); // NOI18N
        testArea.setColumns(20);
        testArea.setForeground(resourceMap.getColor("testArea.foreground")); // NOI18N
        testArea.setRows(5);
        testArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        testArea.setName("testArea"); // NOI18N
        testArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                testAreaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                testAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                testAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(testArea);

        javax.swing.GroupLayout keyPanLayout = new javax.swing.GroupLayout(keyPan);
        keyPan.setLayout(keyPanLayout);
        keyPanLayout.setHorizontalGroup(
            keyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyPanLayout.createSequentialGroup()
                .addGroup(keyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keyPanLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(keyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keyTextGetter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(keyPanLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        keyPanLayout.setVerticalGroup(
            keyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(keyTextGetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keyPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keyPan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testAreaKeyPressed
        // jLabel1.setText("KEY TEXT WHEN PRESSED IS..");
        // keyTextGetter.setText(KeyEvent.getKeyText(evt.getKeyCode()));
    }//GEN-LAST:event_testAreaKeyPressed

    private void testAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testAreaKeyTyped
          jLabel1.setText("KEY TEXT WHEN TYPED IS..");
          keyTextGetter.setText(String.valueOf(evt.getKeyChar()));
    }//GEN-LAST:event_testAreaKeyTyped

    private void testAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testAreaKeyReleased
     // jLabel1.setText("KEY TEXT WHEN RELEASED IS..");
      //  keyTextGetter.setText(KeyEvent.getKeyText(evt.getKeyCode()));
    }//GEN-LAST:event_testAreaKeyReleased

    private void keyPanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyPanMousePressed
   System.out.println(evt.getButton());
    }//GEN-LAST:event_keyPanMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyNameDecoder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel keyPan;
    private javax.swing.JTextField keyTextGetter;
    private javax.swing.JTextArea testArea;
    // End of variables declaration//GEN-END:variables

}
