/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyGraphics.java
 *
 * Created on Aug 19, 2010, 11:25:47 PM
 */

package gui.practisepitch;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author TOPE
 */
public class MyGraphics extends javax.swing.JPanel {
private int counter =0;
private Timer timer;

    /** Creates new form MyGraphics */
    public MyGraphics() {
        initComponents();
        start();
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

public void drawGrid( Graphics g){
    int screenWidth =getWidth();
    int screenHeight =getHeight();
    
    int noOfHorRects=screenWidth/4;
    int noOfVerRects=screenHeight/4;
    
    
    for(int j=0;j<screenHeight;j+=4){  
    for(int i=0;i<screenWidth;i+=4){
        g.drawRect(i,j,4,4 ); 
   }
    }
    
    
}


    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Font f = g.getFont();
        drawGrid(g); 
    int screenWidth =getWidth();
    int screenHeight =getHeight();
    g.setFont( new Font("Arial Bold", Font.BOLD,18) );
    g.setColor(Color.red);

        g.drawLine(0, screenHeight/2, screenWidth, screenHeight/2);
    g.setColor(Color.green);
        g.drawLine(screenWidth/2, 0 , screenWidth/2, screenHeight);

       g.setColor(Color.blue);

g.drawOval(screenWidth/2 -200+counter  , screenHeight/2-200  ,200,200 );



    }


public static void main(String args[]){
    JFrame frame = new JFrame();
    frame.setSize(1300,900);
frame.setVisible(true);
frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
frame.setResizable(false);

MyGraphics gr = new MyGraphics();

frame.add(gr);
System.out.println(0xA2CCFD);

}



public void start(){
    if(timer == null){
        timer = new Timer(1, new TimerHandler());
        timer.start();
    }
    else if(!timer.isRunning()){
        timer.restart();
    }
}

public void stop(){
    if(timer!=null){
        timer.stop();
    }
}


class TimerHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           repaint();
           if(counter<1300){
           counter+=40;
           }
           else{
               counter=0;
           }
        }

}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
