/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel.java
 *
 * Created on Jul 23, 2010, 11:50:51 AM
 */

package gui.practisepitch;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import utils.DraggableBufferedImage;
import utils.ObjectDragger;
/**
 *
 * @author GBEMIRO
 */
public class Panel extends javax.swing.JPanel {
DraggableBufferedImage dbi;
    /** Creates new form Panel */
    public Panel() {
        initComponents(); 
        final JFrame frame = new JFrame();
        setBorder(new BevelBorder(BevelBorder.RAISED));
frame.add(this);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setUndecorated(true);
        frame.setResizable(true);
        frame.setSize(1205,850);
        frame.setVisible(true);
        frame.setLocation(new Point(300,0));
        frame.addMouseListener( new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);
                new ObjectDragger(ObjectDragger.COMPONENT_OBJECT, frame,false);
            }

        });
//this.setSize(40,40);
this.setLocation(0,0);

dbi = new DraggableBufferedImage( new Point(100,50),300, 400, BufferedImage.TYPE_INT_RGB, this);
dbi.loadImage("C:/Users/MRSJIBOYE/Pictures/Astronomy/nasa-1.jpg");


    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(dbi!=null){
        dbi.draw(g);
        }
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(Panel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        // new ObjectDragger(ObjectDragger.IMAGE_OBJECT,dbi,false);
    }//GEN-LAST:event_formMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
     String text = KeyEvent.getKeyText(evt.getKeyCode());
JOptionPane.showMessageDialog(null, text);
    }//GEN-LAST:event_formKeyPressed


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
public static void main(String args[]){
   new Panel();

   System.out.println( Integer.parseInt("A1B2C3", 16));
}
}
