/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClosePanel.java
 *
 * Created on Jul 21, 2010, 2:11:22 PM
 */

package gui.tidBitGraphics;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author GBEMIRO
 */
public class ClosePanel extends javax.swing.JPanel {
    /** Creates new form ClosePanel */
    public ClosePanel() {
        initComponents();
    }





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(ClosePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void paintComponent(Graphics g){
       super.paintComponent(g);
         g.setColor(Color.green);
        g.drawLine(0,0, this.getWidth(), this.getHeight());
        g.drawLine(this.getWidth(),0,0,this.getHeight());
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
