/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TitleBar.java
 *
 * Created on Jul 23, 2010, 8:38:41 AM
 */

package gui.tidBitGraphics;


import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Random;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import utils.ComponentDragger;

/**
 *
 * @author GBEMIRO
 */
public class TitleBar extends javax.swing.JPanel {
private Color bg;
  /** Creates new form TitleBar */
    public TitleBar() {
        initComponents();
        bg=new Color( 102,102,102);

   closePanel1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                closePanel1.setBackground( new Color( new Random().nextInt(256),
                        new Random().nextInt(256),
                        new Random().nextInt(256)) ) ;
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
               closePanel1.setBackground(bg);
            }
            @Override
            public void mousePressed(MouseEvent e) {
            closePanel1.setBorder(new BevelBorder(BevelBorder.LOWERED));
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                super.mouseReleased(e);
               closePanel1.setBorder(new BevelBorder(BevelBorder.RAISED));
            }






   });



    }
    @Override
public void paintComponent(Graphics g){
    super.paintComponent(g);
    writeText(g); 
}

    public void writeText(Graphics g){
        g.setFont( new Font("Kristen ITC",Font.BOLD,20));
        g.drawString("MATHPAD...A=34...E = m*c².. ",6,22);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closePanel1 = new gui.tidBitGraphics.ClosePanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(TitleBar.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setName("Form"); // NOI18N

        closePanel1.setName("closePanel1"); // NOI18N

        javax.swing.GroupLayout closePanel1Layout = new javax.swing.GroupLayout(closePanel1);
        closePanel1.setLayout(closePanel1Layout);
        closePanel1Layout.setHorizontalGroup(
            closePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        closePanel1Layout.setVerticalGroup(
            closePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(closePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @return the object usewd to close the titlebar
 */
    public ClosePanel getClosePanel1() {
        return closePanel1;
    }
/**
 *
 * @param closePanel1 set the object used  to close the title bar
 */
    public void setClosePanel1(ClosePanel closePanel1) {
        this.closePanel1 = closePanel1;
    }







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.tidBitGraphics.ClosePanel closePanel1;
    // End of variables declaration//GEN-END:variables

}
