/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * CommandPrompt.java
 *
 * Created on Aug 29, 2011, 11:20:54 AM
 */
package gui.commandinterface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Point;
import java.util.InputMismatchException;
import javax.swing.JFrame;

/**
 *
 * @author JIBOYE OLUWAGBEMIRO OLAOLUWA
 */
public class CommandPrompt extends javax.swing.JPanel implements Runnable {

    private final Thread timer;

    /**
     * Creates new form CommandPrompt
     */
    public CommandPrompt() {
        initComponents();
        JFrame f = new JFrame("Command Prompt");
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setSize(1000, 900);
        f.addKeyListener(document1);
        f.addMouseListener(document1);
        addMouseListener(document1);
        f.add(this);
        Sentence s = new Sentence(document1);
        s.setText("Hello guys!");
        document1.appendSentence(s);
        document1.setLocation(new Point(100, 200));
        document1.setBgColor(Color.white);
        document1.setFgColor(Color.black);
        document1.setFont(new Font("Calibri", Font.BOLD, 22));
        document1.setSize(new Dimension(1000, 900));
        document1.setMargin(new Dimension(40, 40));
        timer = new Thread(this);
        timer.start();

    }//end constructor

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        document1.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        document1 = new gui.commandinterface.Document();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(nigermath.NigerMathApp.class).getContext().getResourceMap(CommandPrompt.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        area.setColumns(20);
        area.setEditable(false);
        area.setLineWrap(true);
        area.setRows(5);
        area.setFocusable(false);
        area.setName("area"); // NOI18N
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed


    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private gui.commandinterface.Document document1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        new CommandPrompt();
    }

    @Override
    public void run() {
        Thread me = Thread.currentThread();
        while (timer == me) {
            try {
                Thread.currentThread().sleep(500);
            }//end try
            catch (InterruptedException intEx) {

            }//end catch
            repaint();
            area.setText(document1.getCaret().toString()
                    + "\nlineSpacing = " + document1.getLineSpacing() +", text is "+document1.getText()
                    + "\n has " + document1.getText().length() + " characters");

        }//end while loop

    }

}
